/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.qiyi.vrs.vis.h5.thrift.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 缓存实体类型
 * 
 */
public enum EntityType implements org.apache.thrift.TEnum {
  ALBUM(1),
  VIDEO(2),
  RESOURCE(3),
  LIVE_CHANNEL(4),
  LIVE_PROGRAM(5);

  private final int value;

  private EntityType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EntityType findByValue(int value) { 
    switch (value) {
      case 1:
        return ALBUM;
      case 2:
        return VIDEO;
      case 3:
        return RESOURCE;
      case 4:
        return LIVE_CHANNEL;
      case 5:
        return LIVE_PROGRAM;
      default:
        return null;
    }
  }
}
